### ISSUE TITLE
You can try Lombok

### ISSUE THREAD

**Issue by limenitiz** [Girrafeec/CC-QR-Scanner#1]
https://github.com/Girrafeec/CC-QR-Scanner/blob/b7ec558eb9a88b8b4e8af7a7fe51aaaf0de3b6ad/app/src/main/java/com/girrafeecstud/ccqrscanner/ParseCertificateJson.java#L40

For simple getters and setters you can use lombok

Example:

```
import lombok.*;

public class Example {
    @Getter @Setter private Long id;
    @Getter @Setter private String name;
    @Getter @Setter private Integer count;
}
```

**Comment by Girrafeec** [comment]
THX
